spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/login
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#jwt:
#  secret: ${JWT_SECRET}
#  access-expiration-ms: 900000      # 15 minutes
#  refresh-expiration-ms: 1209600000 # 14 jours
#server:
#  ssl:
#    enabled: true